version: '3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: sergapav/foodgram_project:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
  
  frontend:
    image: sergapav/frontend:latest
    volumes:
      - ../frontend:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - static_volume:/var/html/static/
      - media_volume:/var/html/media/

    depends_on:
      - backend

volumes:
   static_volume:
   media_volume:
   data_volume:

